### ISSUE TITLE
reads in prerequisite file 

### ISSUE THREAD

**Issue by rsandean** [csh3/RegCloser#6]
Hi, I understand that there should be forward and reverse reads in the prerequisite file, I was wondering if this tool also took pacbio HiFi reads as I only have one file with these reads in? 

Thank you in advance!

**Comment by csh3** [comment]
I feel sorry about that currently Pacbio HiFi reads are not supported in RegCloser. Thanks for your consideration.

**Comment by rsandean** [comment]
Ah ok thank you for the reply!
